# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sun Guide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sun Guide
pod 'LogRocket', '~> 1.0'

end

target 'SunTrackerExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SunTrackerExtension
  # Pods for Sun Guide
pod 'LogRocket', '~> 1.0'

end
